### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by adit-tama** [geo-python/site#79]
Hi i am trying to follow the lecture in this series and i couldn't find the 029740.txt from the Lesson 7 folder. Where can i get the file?

**Comment by davewhipp** [comment]
Hi! Sorry, just noticed this issue. The file is available following the instructions about downloading the data at the start of the plotting lesson. The command to download the file from a terminal is `wget https://davewhipp.github.io/data/Finland-weather-data-L7.tar.gz`, or you can simply visit the website in a web browser and download the data file that way.

**Comment by davewhipp** [comment]
I'm going to go ahead and close this, assuming the issue is now resolved. If not, let us know.
